services:
  developer:
    build:
      context: .
      dockerfile: dev1/Dockerfile
    container_name: developer
    hostname: developer
    command: ["/home/dev/entrypoint.sh"]
    #command: ["sleep", "infinity"]
    secrets:
      - ssh_key
      - ssh_key_pub
    networks:
      - worldwideNET
      
  developer2:
    build:
      context: .
      dockerfile: dev2/Dockerfile
    container_name: developer2
    hostname: developer2
    command: ["/home/dev2/entrypoint.sh"]
    #[command: "sleep", "infinity"]
    depends_on:
      jump:
        condition: service_healthy
      internal:
        condition: service_healthy
    secrets:
      - ssh_key_dev2
      - ssh_key_dev2_pub
    networks:
      - worldwideNET

  jump:
    build:
      context: .
      dockerfile: jump/Dockerfile
    container_name: jump
    hostname: jump
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 22 || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s
    networks:
      - worldwideNET
      - companyLAN

  internal:
    build:
      context: .
      dockerfile: stage/Dockerfile
    container_name: internal
    hostname: internal
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 22 || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s
    networks:
      - companyLAN

networks:
  worldwideNET:
  companyLAN:
  
secrets:
  ssh_key:
    file: keys/id_ed25519
  ssh_key_pub:
    file: keys/id_ed25519.pub
  ssh_key_dev2:
    file: ./keys/id_dev2
  ssh_key_dev2_pub:
    file: ./keys/id_dev2.pub
