services:
  developer:
    build:
      context: .
      dockerfile: dev1/Dockerfile
    container_name: developer
    hostname: developer
    command: ["sleep", "infinity"]
    #["/home/dev/entrypoint.sh"]
    networks:
      - worldwideNET
      
  developer2:
    build:
      context: .
      dockerfile: dev2/Dockerfile
    container_name: developer2
    hostname: developer2
    command: ["sleep", "infinity"]
    #["/home/dev2/entrypoint.sh"]
    networks:
      - worldwideNET

  jump:
    build:
      context: .
      dockerfile: jump/Dockerfile
    container_name: jump
    hostname: jump
    networks:
      - worldwideNET
      - companyLAN

  internal:
    build:
      context: .
      dockerfile: stage/Dockerfile
    container_name: internal
    hostname: internal
    networks:
      - companyLAN

networks:
  worldwideNET:
  companyLAN:
